id: I9634A78F
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:42:34.735081+00:00
last_modified: 2022-12-15 07:42:34.735087+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-002
  eft-text-version: 1.18 2019
  title: Toh_182-The_Perfection_of_Generosity-v2
bases:
  5A52:
    source_metadata: null
    order: 1
    base_file: 5A52.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
